name: penn-upstream-test
recipe: pantheon
config:
  framework: drupal8
  site: penn-upstream-test
  id: 6440556b-de1e-4232-971c-18d59d201fd4
tooling:
  drupal:
    cmd:
      - "/app/vendor/bin/drupal"
      - "--root=/app/web"
proxy:
  mailhog:
    - mail.penn-upstream-test.lndo.site
services:
  appserver:
    xdebug: true
    config:
      php: .vscode/php.ini
  mailhog:
    type: mailhog
    hogfrom:
      - appserver