name: penn-pep
recipe: pantheon
config:
  framework: drupal8
  site: penn-pep
  id: b5b0278e-12d5-4715-9387-5dc7a0e3ef53
tooling:
  drupal:
    cmd:
      - "/app/vendor/bin/drupal"
      - "--root=/app/web"
proxy:
  mailhog:
    - mail.penn-pep.lndo.site
services:
  appserver:
    xdebug: true
    config:
      php: .vscode/php.ini
  mailhog:
    type: mailhog
    hogfrom:
      - appserver