recipe: pantheon
config:
  framework: drupal9
tooling:
  drupal:
    cmd:
      - "/app/vendor/bin/drupal"
      - "--root=/app/web"
services:
  appserver:
    composer_version: 2-latest
    webroot: web