penn_api_entity.penn_api_entity_type.*:
  type: config_entity
  label: 'Penn API Entity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
